name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /opt/bitnami/wordpress/wp-content/themes &&
            rm -rf credialianza && # Elimina el directorio existente del tema
            git clone https://github.com/Crish777/credialianza.git credialianza && # Clona el repositorio
            echo 'Deployment completed successfully!'
          "
